apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: funda-house-finder-utrecht
  labels:
    name: funda-house-finder
    city: utrecht
spec:
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: funda-house-finder-image-utrecht
    spec:
      containers:
      - image: us.gcr.io/bad-air/funda_house_finder:v0.3
        name: funda-house-finder-utrecht
        resources:
          requests:
            cpu: "20m"
            memory: "120M"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 10
        env:
        - name:  HOUSE_FINDER_URL
          value:  "www.funda.nl"
        - name: HOUSE_FINDER_PATH
          value: "/huur/utrecht/+5km/700-1250/sorteer-datum-af/"
        imagePullPolicy: IfNotPresent